   array.php
   conditioning.php
   constant.php
   dataTypes.php
   function.php
   hello.php
   looping.php
   number.php
   output.php
   sortingArr.php
   string.php
   superglobal.php
   variable.php
